version: '3.9'

services:
  backend:
    build:
      context: ./Technothon_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Technothon_backend:/app
    restart: always

  frontend:
    build:
      context: ./Technothon_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
